export enum Role {

	ADMIN = "ROLE_ADMIN", PEDAGOGICO = "ROLE_PEDAGOGICO", GRADUACAO = "ROLE_GRADUACAO", RH = "ROLE_RH",
	DISCENTE = "ROLE_DISCENTE", DOCENTE = "ROLE_DOCENTE", VESTIBULANDO = "ROLE_VESTIBULANDO", USER = "ROLE_USER"

}
